services:
  web:
    build: web/
    ports:
      - "8000:8000"
  postgres:
    image: postgres
    ports:
      - "6401:5432"
    env_file: .env
    volumes:
      - pg-data:/data/postgres

volumes:
  pg-data:
